
import javax.swing.JTextArea;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bhaskar
 */
public class DisplayResult extends javax.swing.JFrame {

    /**
     * Creates new form DisplayResult
     */
    
    public static int population = 20;
    public static double mutationRate=0.015;
    public static int groupSize=5;
    
    String selectedPlaces = "BILASPUR\nHAMIRPUR";
    public DisplayResult() {
        initComponents();
        groupText.setText("5");
        populationText.setText("20");
        mutationText.setText("0.015");
    }
    public DisplayResult(String selectedPlaces) {
       
        this.selectedPlaces=selectedPlaces;
        initComponents();
        groupText.setText("5");
        populationText.setText("20");
        mutationText.setText("0.015");
    }
    public DisplayResult(String selectedPlaces,JTextArea outSelectArea) {
       
        this.selectedPlaces=selectedPlaces;
        this.outTextArea=outSelectArea;
        initComponents();
        groupText.setText("5");
        populationText.setText("20");
        mutationText.setText("0.015");
        
        }

     public void showResult()
    {
        
        //getting the parameters values
        
         //algoEvaluation out = new algoEvaluation();  // creating object of algorithm evaluation class (jform)..
        // out.setVisible(true);
        
        long startTime=System.currentTimeMillis();
        
        
         HPTOUR_GA objectHP = new HPTOUR_GA(selectedPlaces,displayResult,outTextArea);
             
         objectHP.findOptimalTour();
         
         long endTime=System.currentTimeMillis();
         
         long timeElapsed=endTime-startTime;
         
         outTextArea.append("\n\nExecution Time :"+timeElapsed+"ms\n\n");
         outTextArea.update(outTextArea.getGraphics());
                
    }
    
    public void showResultRandom()
    {
        //double m = Double.parseDouble(mutationText.getText().toString());
        
            /*this.outTextArea.setText("");
        
            outTextArea.update(outTextArea.getGraphics());*/
        
            long startTime=System.currentTimeMillis();
            
            this.mutationRate=Double.parseDouble(mutationText.getText().toString());
            this.population=Integer.parseInt(populationText.getText().toString());
            this.groupSize=Integer.parseInt(groupText.getText().toString());
            
            if(population!=0&&groupSize!=0)
            {    
                   HPTOUR_GA objectHP = new HPTOUR_GA(selectedPlaces,displayResult,mutationRate,groupSize,population,outTextArea);
                   objectHP.findOptimalTour();
            }
        
            else
            {
                populationText.setText("");
                mutationText.setText("");
                groupText.setText("");
            }
            
            long endTime=System.currentTimeMillis();
            long timeElapsed=endTime-startTime;
            
            outTextArea.append("\n\nExecution Time : "+timeElapsed+"ms\n\n");
            outTextArea.update(outTextArea.getGraphics());
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        suggestedLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayResult = new javax.swing.JTextArea();
        nearbyplaces = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        populationText = new javax.swing.JTextField();
        mutationText = new javax.swing.JTextField();
        groupText = new javax.swing.JTextField();
        randomButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CLEARBUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 598));

        suggestedLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        suggestedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suggestedLabel.setText("  Suggested Tour  (Using Genetic Algorithm)");

        returnButton.setForeground(new java.awt.Color(9, 52, 246));
        returnButton.setText("New Tour");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        displayResult.setColumns(20);
        displayResult.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        displayResult.setForeground(new java.awt.Color(74, 102, 169));
        displayResult.setRows(5);
        jScrollPane1.setViewportView(displayResult);

        nearbyplaces.setForeground(new java.awt.Color(5, 45, 246));
        nearbyplaces.setText("Nearby Places");
        nearbyplaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearbyplacesActionPerformed(evt);
            }
        });

        outTextArea.setEditable(false);
        outTextArea.setColumns(20);
        outTextArea.setRows(5);
        jScrollPane2.setViewportView(outTextArea);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALGORITHM EVALUATION");

        jPanel2.setForeground(new java.awt.Color(44, 44, 44));

        randomButton.setForeground(new java.awt.Color(9, 43, 254));
        randomButton.setText("Random Tour");
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("POPULATON");

        jLabel3.setText("MUTATION RATE");

        jLabel4.setText("GROUP SIZE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(groupText, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(mutationText)
                            .addComponent(populationText)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(randomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(populationText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mutationText)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(groupText)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(randomButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        CLEARBUTTON.setForeground(new java.awt.Color(6, 63, 254));
        CLEARBUTTON.setText("CLEAR");
        CLEARBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(suggestedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nearbyplaces)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CLEARBUTTON))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suggestedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLEARBUTTON))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nearbyplaces)
                            .addComponent(returnButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        new WelcomeClass().setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        // TODO add your handling code here:
            
            this.showResultRandom();
    }//GEN-LAST:event_randomButtonActionPerformed

    private void nearbyplacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearbyplacesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        nearby objectn = new nearby(selectedPlaces);
        objectn.setVisible(true);
    }//GEN-LAST:event_nearbyplacesActionPerformed

    private void CLEARBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARBUTTONActionPerformed
        // TODO add your handling code here:
        this.outTextArea.setText("");
        
        outTextArea.update(outTextArea.getGraphics());
        
    }//GEN-LAST:event_CLEARBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            
            public void run() {
         
               new DisplayResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEARBUTTON;
    private javax.swing.JTextArea displayResult;
    private javax.swing.JTextField groupText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mutationText;
    private javax.swing.JButton nearbyplaces;
    private javax.swing.JTextArea outTextArea;
    private javax.swing.JTextField populationText;
    private javax.swing.JButton randomButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel suggestedLabel;
    // End of variables declaration//GEN-END:variables
}
